### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KangchengHou** [KangchengHou/calpred-manuscript#2]
Simulations:
- [x] conformal calibration with empirical prediction interval from 500 posterior samples.
- [x] conformal calibration with analytical prediction interval as a function of PCs.
- [x] conformal calibration as a function of age, sex and PC1 (with some simulated effect)
- [ ] pipeline work with case control phenotype
- [ ] pipeline work with survival data / absolute risk prediction

Overall is to show we can have a pipeline that robust outputs calibrated prediction interval without *any* sacrifice on the performance.

Real studies:
- [x] conformal calibration as a function of age, sex and PC1 (with some simulated effect)
- [ ] example to show it does help in downstream task.

Software:
- [ ] provide a PC map such that user can easily project to their own genotypes.

Writing:
- [ ] rewrite the equation using SVD decomposition, also check GP literature
